config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  get 'admin', to: 'pages#admin'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'  

  resources :doctors do
    member do
      get :like
      get :unlike
    end
  end

  resources :patients
  devise_for :users, controllers: { registrations: "registrations" }

  get 'home/index'

  root 'home#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user

  validates :first_name, :surname, :address, :phone, :suburb, :postcode, :state, presence: true

  geocoded_by :full_street_address
  after_validation :geocode 



  def full_name
  	[first_name, surname].compact.join(' ')
  end


  def full_street_address
  	[address, suburb, state, postcode, country].compact.join(', ')
  end	
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.user = current_user

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:user_id, :first_name, :surname, :phone, :medicare_number, :address, :suburb, :state, :postcode, :country, :latitude, :longitude)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= simple_form_for(@patient) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-md-6">
       <%= f.input :first_name %>
    </div>

    <div class="col-md-6">
    <%= f.input :surname %>
    </div>

    <div class="row">
    <div class="col-md-6">
    <%= f.input :phone %>
    </div>

        <div class="col-md-6">
    <%= f.input :medicare_number %>
</div>

  <div class="row">
    <div class="col-md-6">
    <%= f.input :address %>
    </div>

        <div class="col-md-6">
    <%= f.input :suburb %>
    </div>

    <div class="row">
    <div class="col-md-4">
    <%= f.input :state, collection: ['QLD', 'NSW', 'VIC'] %>
    </div>

            <div class="col-md-4">
    <%= f.input :postcode %>
    </div>

        <div class="col-md-4">
    <%= f.input :country, priority: ['Australia', 'New Zealand'] %>
    </div>
    
  </div>

    <div class="row">
    <div class="col-md-12">
    <%= f.button :submit %>
  </div>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Surname</th>
      <th>Phone</th>
      <th>Medicare number</th>
      <th>Address</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.user %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.surname %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.medicare_number %></td>
        <td><%= patient.address %></td>
        <td><%= patient.suburb %></td>
        <td><%= patient.state %></td>
        <td><%= patient.postcode %></td>
        <td><%= patient.country %></td>
        <td><%= patient.latitude %></td>
        <td><%= patient.longitude %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<div class="row">

<div class="col-md-8 col-md-offset-2">
<div class="panel panel-info">
 <div class="panel-heading">
   <h2 class="panel-title">Register</h2>
</div>

<div class="panel-body">

<%= render 'form' %>

</div>
</div>
</div>
</div>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

<div class="col-md-4">
<div class="panel panel-info">
 <div class="panel-heading">

<h2 class="panel-title">Your profile</h2>
</div>

<div class="panel-body">

<p>
  <strong><%= @patient.full_name %></strong>
  
</p>



<p>
  <strong>Email:</strong>
  <%= @patient.user.email %>
</p>


<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Medicare number:</strong>
  <%= @patient.medicare_number %>
</p>

<p>
  
  <%= @patient.address %>
  <%= @patient.suburb %> <%= @patient.state %> 
  <%= @patient.postcode %> <%= @patient.country %>

</p>


</div>
</div></div></div>






<%= link_to 'Edit', edit_patient_path(@patient), class: 'btn btn-xs' %> 
</div>