config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  get 'admin', to: 'pages#admin'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'  

  resources :doctors do
    member do
      get :like
      get :unlike
    end
  end

  resources :patients
  devise_for :users, controllers: { registrations: "registrations" }

  get 'home/index'

  root 'home#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :user


  mount_uploader :photo, DoctorPhotoUploader

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  acts_as_taggable

  acts_as_votable

  def full_name
  	[first_name, last_name, post_nominals].compact.join(' ')
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:unlike, :like, :show, :edit, :update, :destroy]

def like
  @doctor.liked_by current_user
  redirect_to :back

end

def unlike
  @doctor.unliked_by current_user
  redirect_to :back
end

  # GET /doctors
  # GET /doctors.json
  def index
    if params[:tag]
      @doctors = Doctor.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 3)

    else
    @doctors = Doctor.paginate(:page => params[:page], :per_page => 3)

  end
end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:title, :first_name, :last_name, :post_nominals, :bio, :photo, :user_id, :tag_list)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= simple_form_for(@doctor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :post_nominals %>
    <%= f.input :bio %>
    <%= f.input :photo %>
    <%= f.input :tag_list, input_html: { value: @doctor.tag_list.to_s} %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>



<div class="row">
<div class="col-md-2">

 <% Doctor.tag_counts_on(:tags).each do |tag| %>

   <%= link_to tag.name + ' (' +tag.count.to_s + ')', doctors_path(tag: tag.name), class: 'btn btn-info btn-sm' %>
   <br>
   <% end %>
   <%= link_to "All doctors", doctors_path, class: 'btn btn-warning btn-sm' %>
   </div>

<div class="col-md-8">
<div class="panel panel-info">
 <div class="panel-body">

<h1>Listing Doctors</h1>

<table class="table table-hover">


  <thead>
    <tr>
      <th>Doctor</th>
     
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= link_to doctor.full_name, doctor %></td>
        <td><%= doctor.photo %></td>
        
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @doctors, class: 'flickr_pagination' %>


<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
 <div class="col-md-4">

<%= image_tag @doctor.photo, class: 'img-responsive img-thumbnail' %>


<p>
  <strong>Title:</strong>
  <%= @doctor.title %>
</p>

<p>
  <strong>First name:</strong>
  <%= @doctor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @doctor.last_name %>
</p>

<p>
  <strong>Post nominals:</strong>
  <%= @doctor.post_nominals %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @doctor.bio %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @doctor.photo %>
</p>

<p>
  <strong>Specialties</strong>


  <ul>
   <% @doctor.tags.each do |tag| %>
   <li><%= link_to tag.name, doctors_path(tag: tag.name) %></li>
   <% end %>
   </ul>
</p>

<% if current_user.voted_for? @doctor %>


<%= link_to 'Unlike', unlike_doctor_path(@doctor), class: 'btn btn-success btn-sm' %>
<% else %>

<%= link_to 'Like', like_doctor_path(@doctor), class: 'btn btn-success btn-sm' %>
<% end %>

<p>Likes: <%= @doctor.votes_for.size %> </p>


<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>