config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  get 'admin', to: 'pages#admin'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'  

  resources :doctors do
    member do
      get :like
      get :unlike
    end
  end

  resources :patients
  devise_for :users, controllers: { registrations: "registrations" }

  get 'home/index'

  root 'home#index'

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
	validates :name, :email, :message, presence: true
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    respond_to do |format|
      if @enquiry.save
        EnquiryMailer.response(@enquiry.id).deliver_now
        EnquiryMailer.received(@enquiry.id).deliver_now
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:email, :name, :message, :phone, :enquiry_type)
    end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= simple_form_for(@enquiry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :name %>
    <%= f.input :message %>
    <%= f.input :phone %>
    <%= f.input :enquiry_type, collection: ['Appointment query', 'Cancellation', 'Website error', 'Other'] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Message</th>
      <th>Phone</th>
      <th>Enquiry type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.email %></td>
        <td><%= enquiry.name %></td>
        <td><%= enquiry.message %></td>
        <td><%= enquiry.phone %></td>
        <td><%= enquiry.enquiry_type %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enquiry.message %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @enquiry.phone %>
</p>

<p>
  <strong>Enquiry type:</strong>
  <%= @enquiry.enquiry_type %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>